keys:
  - &laptop_maddux age1qrwmet65j048nzg29n7u8yl50vvpr2w57nnqdnxe3hfxek7jegcq4yjz68
  - &host_laptop age17yqaa9ju8qty8vw9asz9aes3v5ryslqfzaw9lewpf6lhycgemussftwtef
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *laptop_maddux
        - *host_laptop
