keys:
  - &host_laptop age1a39uu7zpq79y44e4005t3s5tk8uhnpe7lp66zjvsx4d0z2qxwc5sylh5rq
  - &host_media-center age1vx72v97nzylnhm7lla7m2zhg44cwtzn86nupfhqp6hjwhnx2ssfs7aymtc
  - &host_blocky age1fw03qngjkn9ry79agqhqv365scf0fhc2h0wd2k9y2ksnszfd432swn3uf5
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *host_laptop
        - *host_media-center
        - *host_blocky
