keys:
  - &host_laptop age1a39uu7zpq79y44e4005t3s5tk8uhnpe7lp66zjvsx4d0z2qxwc5sylh5rq
  - &host_automata age1m9faped3zgvvnz285janjgfg6d9c43wy67uzs4yggugp6augxapqdn7fdz
  - &host_media-center age1ck8dr50rr5svhkx2kqc67593c380gmh5f2s0sjm7qc9lnelcx4ysaz9r00
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *host_laptop
        - *host_media-center
        - *host_automata
